name: Build and deploy the Docker image

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Docker Build and Push the snapshot image
        run: docker buildx build --push -f Dockerfile --tag kwart/innosetup:latest .
